# Generated by Django 3.2.3 on 2021-06-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentary',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.RenameField(
            model_name='commentary',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='commentary',
            name='title',
        ),
        migrations.AddField(
            model_name='commentary',
            name='value',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='text',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Комментарий'),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
