# Generated by Django 3.2.3 on 2021-06-19 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0002_auto_20210619_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='shoes.commentary', verbose_name='ID комментария родителя'),
        ),
    ]
