# Generated by Django 3.2.3 on 2021-06-19 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0005_alter_commentary_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoes',
            old_name='url',
            new_name='slug',
        ),
    ]
