# Generated by Django 3.2.3 on 2021-06-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0006_rename_url_shoes_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания или обновления'),
        ),
    ]
