# Generated by Django 3.2.3 on 2021-08-05 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0009_alter_answer_commentary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='commentary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoes.commentary', verbose_name='ID родителя отзыва'),
        ),
    ]
