# Generated by Django 3.2.3 on 2021-09-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0012_alter_shoes_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='sex',
            field=models.CharField(choices=[('1', 'мальчик'), ('2', 'девочка')], default='девочка', max_length=100, verbose_name='Пол'),
        ),
    ]
