# Generated by Django 3.2.3 on 2021-06-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Стоимость заказа')),
                ('payment', models.BooleanField(default=0, help_text='0 - онлайн перевод, 1 - наложенный платеж')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
                ('post_type', models.CharField(max_length=50, verbose_name='Тип доставки')),
                ('status', models.CharField(max_length=50, verbose_name='Статус заказа')),
                ('commentary', models.TextField(blank=True, max_length=500, verbose_name='Комментарии к заказу')),
                ('cart', models.ManyToManyField(to='cart.Cart', verbose_name='Товары с корзины')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
